# Config copiata nell'immagine invece che bind-mountata: su Docker Desktop
# Windows i bind-mount di file singoli danno problemi.
FROM eclipse-mosquitto:2

COPY config/mosquitto/mosquitto.conf /mosquitto/config/mosquitto.conf
